In [20]:
import pandas as pd

In [21]:
# Carrega o CSV
df = pd.read_csv("Social Progress Index 2022.csv")

In [22]:
df.head()

,Rank,Country,Social Progress Score,Basic Human Needs,Foundations of Wellbeing,Opportunity,Nutrition and Basic Medical Care,Water and Sanitation,Shelter,Personal Safety,Access to Basic Knowledge,Access to Information and Communications,Health and Wellness,Environmental Quality,Personal Rights,Personal Freedom and Choice,Inclusiveness,Access to Advanced Education
0,1,Norway,90.74,91.26,90.86,90.11,93.89,98.80,91.59,80.76,98.69,96.12,88.73,79.91,95.63,88.95,92.04,83.81
1,2,Denmark,90.54,91.81,90.32,89.48,95.33,97.36,94.32,80.22,97.47,97.69,84.65,81.45,98.10,88.86,88.44,82.53
2,3,Finland,90.46,91.36,90.31,89.71,93.22,98.45,95.79,77.98,96.31,95.72,84.08,85.14,96.97,89.26,89.29,83.33
3,4,Switzerland,90.26,91.35,91.26,88.16,93.85,98.12,92.12,81.31,98.65,94.99,90.84,80.56,94.65,90.14,86.58,81.26
4,5,Iceland,89.54,91.18,90.44,87.00,93.26,98.97,91.59,80.88,99.47,92.68,88.28,81.31,95.10,88.13,87.46,77.32

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 18 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Rank                                      169 non-null    int64
 1   Country                                   169 non-null    object
 2   Social Progress Score                     169 non-null    float64
 3   Basic Human Needs                         169 non-null    float64
 4   Foundations of Wellbeing                  169 non-null    float64
 5   Opportunity                               169 non-null    float64
 6   Nutrition and Basic Medical Care          169 non-null    float64
 7   Water and Sanitation                      169 non-null    float64
 8   Shelter                                   169 non-null    float64
 9   Personal Safety                           169 non-null    float64
 10  Access to Basic Knowledge                 169 non-null    float64
 11  Access to Information and Communications  169 non-null    float64
 12  Health and Wellness                       169 non-null    float64
 13  Environmental Quality                     169 non-null    float64
 14  Personal Rights                           169 non-null    float64
 15  Personal Freedom and Choice               169 non-null    float64
 16  Inclusiveness                             169 non-null    float64
 17  Access to Advanced Education              169 non-null    float64
dtypes: float64(16), int64(1), object(1)
memory usage: 23.9+ KB

In [24]:
print(df.describe())

             Rank  Social Progress Score  Basic Human Needs  \
count  169.000000             169.000000         169.000000
mean    85.000000              66.097219          74.524024
std     48.930222              14.832700          14.907809
min      1.000000              30.650000          28.960000
25%     43.000000              54.010000          62.420000
50%     85.000000              67.150000          80.370000
75%    127.000000              76.890000          86.510000
max    169.000000              90.740000          92.910000

       Foundations of Wellbeing  Opportunity  \
count                169.000000   169.000000
mean                  65.554852    58.213018
std                   15.192986    17.208466
min                   30.050000    22.250000
25%                   52.970000    46.060000
50%                   66.370000    55.960000
75%                   76.930000    70.590000
max                   91.260000    90.110000

       Nutrition and Basic Medical Care  Water and Sanitation     Shelter  \
count                        169.000000            169.000000  169.000000
mean                          81.689053             78.411243   75.804497
std                           13.663133             17.913268   19.450927
min                           36.380000             21.970000   21.130000
25%                           69.990000             66.480000   61.330000
50%                           86.650000             86.340000   86.350000
75%                           93.220000             92.020000   89.840000
max                           97.640000             98.970000   96.530000

       Personal Safety  Access to Basic Knowledge  \
count       169.000000                 169.000000
mean         62.191302                  75.064024
std          12.017411                  19.103642
min          32.470000                  24.950000
25%          53.390000                  62.580000
50%          62.440000                  79.720000
75%          72.690000                  91.410000
max          83.200000                  99.470000

       Access to Information and Communications  Health and Wellness  \
count                                169.000000           169.000000
mean                                  69.846095            58.329112
std                                   19.829022            16.714558
min                                    8.160000            18.210000
25%                                   55.190000            45.550000
50%                                   75.420000            57.120000
75%                                   85.170000            69.740000
max                                   98.540000            90.840000

       Environmental Quality  Personal Rights  Personal Freedom and Choice  \
count             169.000000       169.000000                   169.000000
mean               58.979112        68.894438                    63.215799
std                13.034548        22.327370                    14.600438
min                20.350000        13.070000                    28.640000
25%                51.200000        53.430000                    54.620000
50%                58.660000        73.660000                    62.800000
75%                68.330000        88.510000                    73.510000
max                85.140000        98.100000                    90.140000

       Inclusiveness  Access to Advanced Education
count     169.000000                    169.000000
mean       49.354379                     51.387101
std        20.465027                     19.006811
min         5.900000                     17.640000
25%        34.180000                     33.580000
50%        48.560000                     51.560000
75%        63.650000                     67.630000
max        92.040000                     87.290000

In [25]:
df[df["Country"] == "Spain"].T

                                             20
Rank                                         21
Country                                   Spain
Social Progress Score                     85.35
Basic Human Needs                         89.52
Foundations of Wellbeing                  84.71
Opportunity                               81.81
Nutrition and Basic Medical Care           96.2
Water and Sanitation                      92.22
Shelter                                   88.21
Personal Safety                           81.43
Access to Basic Knowledge                 88.56
Access to Information and Communications  91.56
Health and Wellness                       83.02
Environmental Quality                      75.7
Personal Rights                           93.24
Personal Freedom and Choice               80.87
Inclusiveness                             75.91
Access to Advanced Education              77.21

In [26]:
df.describe()

,Rank,Social Progress Score,Basic Human Needs,Foundations of Wellbeing,Opportunity,Nutrition and Basic Medical Care,Water and Sanitation,Shelter,Personal Safety,Access to Basic Knowledge,Access to Information and Communications,Health and Wellness,Environmental Quality,Personal Rights,Personal Freedom and Choice,Inclusiveness,Access to Advanced Education
count,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000,169.000000
mean,85.000000,66.097219,74.524024,65.554852,58.213018,81.689053,78.411243,75.804497,62.191302,75.064024,69.846095,58.329112,58.979112,68.894438,63.215799,49.354379,51.387101
std,48.930222,14.832700,14.907809,15.192986,17.208466,13.663133,17.913268,19.450927,12.017411,19.103642,19.829022,16.714558,13.034548,22.327370,14.600438,20.465027,19.006811
min,1.000000,30.650000,28.960000,30.050000,22.250000,36.380000,21.970000,21.130000,32.470000,24.950000,8.160000,18.210000,20.350000,13.070000,28.640000,5.900000,17.640000
25%,43.000000,54.010000,62.420000,52.970000,46.060000,69.990000,66.480000,61.330000,53.390000,62.580000,55.190000,45.550000,51.200000,53.430000,54.620000,34.180000,33.580000
50%,85.000000,67.150000,80.370000,66.370000,55.960000,86.650000,86.340000,86.350000,62.440000,79.720000,75.420000,57.120000,58.660000,73.660000,62.800000,48.560000,51.560000
75%,127.000000,76.890000,86.510000,76.930000,70.590000,93.220000,92.020000,89.840000,72.690000,91.410000,85.170000,69.740000,68.330000,88.510000,73.510000,63.650000,67.630000
max,169.000000,90.740000,92.910000,91.260000,90.110000,97.640000,98.970000,96.530000,83.200000,99.470000,98.540000,90.840000,85.140000,98.100000,90.140000,92.040000,87.290000

In [27]:
print("Forma del dataset:", df.shape)

Forma del dataset: (169, 18)

In [28]:
print("Columnas disponibles:", df.columns.tolist())

Columnas disponibles: ['Rank', 'Country', 'Social Progress Score', 'Basic Human Needs', 'Foundations of Wellbeing', 'Opportunity', 'Nutrition and Basic Medical Care', 'Water and Sanitation', 'Shelter', 'Personal Safety', 'Access to Basic Knowledge', 'Access to Information and Communications', 'Health and Wellness', 'Environmental Quality', 'Personal Rights', 'Personal Freedom and Choice', 'Inclusiveness', 'Access to Advanced Education']

In [29]:
df.columns

Index(['Rank', 'Country', 'Social Progress Score', 'Basic Human Needs',
       'Foundations of Wellbeing', 'Opportunity',
       'Nutrition and Basic Medical Care', 'Water and Sanitation', 'Shelter',
       'Personal Safety', 'Access to Basic Knowledge',
       'Access to Information and Communications', 'Health and Wellness',
       'Environmental Quality', 'Personal Rights',
       'Personal Freedom and Choice', 'Inclusiveness',
       'Access to Advanced Education'],
      dtype='object')

In [30]:
df.isnull().sum()

Rank                                        0
Country                                     0
Social Progress Score                       0
Basic Human Needs                           0
Foundations of Wellbeing                    0
Opportunity                                 0
Nutrition and Basic Medical Care            0
Water and Sanitation                        0
Shelter                                     0
Personal Safety                             0
Access to Basic Knowledge                   0
Access to Information and Communications    0
Health and Wellness                         0
Environmental Quality                       0
Personal Rights                             0
Personal Freedom and Choice                 0
Inclusiveness                               0
Access to Advanced Education                0
dtype: int64

In [31]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
164    False
165    False
166    False
167    False
168    False
Length: 169, dtype: bool

In [32]:
df.nunique().sort_values(ascending=False)

Rank                                        169
Country                                     169
Social Progress Score                       168
Inclusiveness                               168
Personal Rights                             168
Environmental Quality                       168
Access to Information and Communications    168
Access to Basic Knowledge                   167
Personal Safety                             167
Opportunity                                 167
Health and Wellness                         166
Access to Advanced Education                166
Foundations of Wellbeing                    165
Nutrition and Basic Medical Care            164
Basic Human Needs                           164
Water and Sanitation                        163
Personal Freedom and Choice                 162
Shelter                                     158
dtype: int64

In [33]:
df.head()

,Rank,Country,Social Progress Score,Basic Human Needs,Foundations of Wellbeing,Opportunity,Nutrition and Basic Medical Care,Water and Sanitation,Shelter,Personal Safety,Access to Basic Knowledge,Access to Information and Communications,Health and Wellness,Environmental Quality,Personal Rights,Personal Freedom and Choice,Inclusiveness,Access to Advanced Education
0,1,Norway,90.74,91.26,90.86,90.11,93.89,98.80,91.59,80.76,98.69,96.12,88.73,79.91,95.63,88.95,92.04,83.81
1,2,Denmark,90.54,91.81,90.32,89.48,95.33,97.36,94.32,80.22,97.47,97.69,84.65,81.45,98.10,88.86,88.44,82.53
2,3,Finland,90.46,91.36,90.31,89.71,93.22,98.45,95.79,77.98,96.31,95.72,84.08,85.14,96.97,89.26,89.29,83.33
3,4,Switzerland,90.26,91.35,91.26,88.16,93.85,98.12,92.12,81.31,98.65,94.99,90.84,80.56,94.65,90.14,86.58,81.26
4,5,Iceland,89.54,91.18,90.44,87.00,93.26,98.97,91.59,80.88,99.47,92.68,88.28,81.31,95.10,88.13,87.46,77.32

In [34]:
df.sample(5)

,Rank,Country,Social Progress Score,Basic Human Needs,Foundations of Wellbeing,Opportunity,Nutrition and Basic Medical Care,Water and Sanitation,Shelter,Personal Safety,Access to Basic Knowledge,Access to Information and Communications,Health and Wellness,Environmental Quality,Personal Rights,Personal Freedom and Choice,Inclusiveness,Access to Advanced Education
137,138,Cameroon,51.40,56.19,51.63,46.37,70.32,52.98,58.05,43.41,69.54,56.88,43.03,37.07,60.26,51.33,41.03,32.87
56,57,Jamaica,73.48,81.22,71.38,67.85,88.56,81.79,85.69,68.83,87.00,71.71,61.96,64.86,88.26,69.27,62.29,51.56
113,114,Venezuela,58.62,71.77,57.96,46.12,80.31,76.44,84.19,46.12,73.68,47.29,49.07,61.82,41.26,59.58,43.53,40.14
74,75,Cabo Verde,69.01,78.21,63.81,65.01,85.33,82.56,83.58,61.37,67.06,71.08,62.37,54.71,90.06,70.30,59.45,40.22
146,147,Mozambique,48.27,50.81,51.03,42.97,57.67,53.65,41.90,50.03,59.62,43.31,40.73,60.44,61.64,42.02,41.73,26.49

In [35]:
df.tail(5)

,Rank,Country,Social Progress Score,Basic Human Needs,Foundations of Wellbeing,Opportunity,Nutrition and Basic Medical Care,Water and Sanitation,Shelter,Personal Safety,Access to Basic Knowledge,Access to Information and Communications,Health and Wellness,Environmental Quality,Personal Rights,Personal Freedom and Choice,Inclusiveness,Access to Advanced Education
164,165,Somalia,35.85,43.34,37.44,26.77,47.10,47.15,34.36,44.74,27.88,36.57,28.52,56.78,30.45,31.49,17.75,27.39
165,166,Eritrea,34.85,48.16,34.16,22.25,59.34,40.23,49.27,43.80,37.19,16.90,34.94,47.60,13.07,33.82,23.01,19.08
166,167,Chad,34.69,37.70,36.68,29.70,49.03,25.17,29.35,47.25,25.64,35.75,37.20,48.12,47.09,28.68,21.36,21.66
167,168,Central African Republic,32.39,28.96,33.29,34.91,36.38,21.97,21.13,36.37,38.48,27.79,18.21,48.68,56.58,29.20,30.39,23.47
168,169,South Sudan,30.65,38.70,30.05,23.19,58.87,32.67,27.61,35.67,27.24,8.16,29.89,54.90,32.36,28.64,14.13,17.64

In [37]:
df.set_index("Rank", inplace=True)

In [38]:
df.head()

,Country,Social Progress Score,Basic Human Needs,Foundations of Wellbeing,Opportunity,Nutrition and Basic Medical Care,Water and Sanitation,Shelter,Personal Safety,Access to Basic Knowledge,Access to Information and Communications,Health and Wellness,Environmental Quality,Personal Rights,Personal Freedom and Choice,Inclusiveness,Access to Advanced Education
Rank,,,,,,,,,,,,,,,,,
1,Norway,90.74,91.26,90.86,90.11,93.89,98.80,91.59,80.76,98.69,96.12,88.73,79.91,95.63,88.95,92.04,83.81
2,Denmark,90.54,91.81,90.32,89.48,95.33,97.36,94.32,80.22,97.47,97.69,84.65,81.45,98.10,88.86,88.44,82.53
3,Finland,90.46,91.36,90.31,89.71,93.22,98.45,95.79,77.98,96.31,95.72,84.08,85.14,96.97,89.26,89.29,83.33
4,Switzerland,90.26,91.35,91.26,88.16,93.85,98.12,92.12,81.31,98.65,94.99,90.84,80.56,94.65,90.14,86.58,81.26
5,Iceland,89.54,91.18,90.44,87.00,93.26,98.97,91.59,80.88,99.47,92.68,88.28,81.31,95.10,88.13,87.46,77.32